[package]
name = "aiwriteclicheck"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.14"
termcolor = "1.1.0"
content_inspector = "0.2.4"